version: '3'

services:
  postgres-notes:
    image: postgres:latest
    container_name: postgres-notes
    ports:
      - "5432:5432"   
    environment:
      POSTGRES_DB: note
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  backend:
    build:
       context: ./backend-notes
       dockerfile: Dockerfile
    container_name: backend
    command: java -jar app.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-notes:5432/note
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on: 
      - postgres-notes